name: Bug report
description: Create a report to help us improve
labels: 'Type: bug'

body:
  - type: markdown
    attributes:
      value: |
        Before reporting an issue make sure you are running the latest build of the plugin and checked for duplicate issues!

  - type: textarea
    attributes:
      label: What behaviour is observed?
      description: A clear and concise description of what the behavior is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behaviour
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: To Reproduce
      description: Steps to reproduce this behaviour
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    attributes:
      label: Plugin list
      description: This can be found by running `/pl`
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Server Implementation
      description: Which server implementation are you using?
      multiple: false
      options:
        - Standalone server (no proxy)
        - BungeeCord
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Database Implementation
      description: Which database implementation are you using?
      multiple: false
      options:
        - SQLite
        - MySQL
    validations:
      required: true

  - type: input
    attributes:
      label: AuthMe Version
      description: What version of AuthMe are you running? (`/authme version`)
    validations:
      required: true

  - type: input
    attributes:
      label: Error log (if applicable)
      description: If you are reporting a console error, upload any relevant log excerpts to either https://paste.gg/ or https://gist.github.com, save and the paste the link in this box.

  - type: input
    attributes:
      label: Configuration
      description: Link of your config.yml file (remember to delete any sensitive data), upload any relevant log excerpts to either https://paste.gg/ or https://gist.github.com, save and the paste the link in this box.
    validations:
      required: true
