name: AuthMe
author: darkwarriros,Xephi
website: http://www.multiplayer-italia.com/
description: AuthMe prevents people, which aren't logged in, from doing stuff like placing blocks, moving, typing commands or seeing the inventory of the current player.
main: uk.org.whoami.authme.AuthMe
version: 2.7.2b3
softdepend: [Vault]
commands:
    register:
        description: Register an account
        usage: /register password confirmpassword
        aliases: reg
    login:
        description: Login into a account
        usage: /login password
        aliases: l
    changepassword:
        description: Change password of a account
        usage: /changepassword oldPassword newPassword
    logout:
        description: Logout
        usage: /logout
    unregister:
        description: unregister your account
        usage: /unregister password    
    passpartu:
        description: compare passpartu token
        usage: /passpartu token          
    authme:
        description: AuthMe op commands
        usage: '/authme reload|register playername password|changepassword playername password|unregister playername|version'
permissions:
    authme.player.*:
        description: Gives access to all authme player commands
        default: true
        children:
            authme.register: true
            authme.login: true
            authme.changepassword: true
            authme.logout: true
            authme.unregister: true
            authme.passpartu: true
            authme.l: true
            authme.reg: true
    authme.admin.*:
         description: Gives access to all authme admin commands
         children:
             authme.admin.reload: true
             authme.admin.register: true
             authme.admin.changepassword: true
             authme.admin.unregister: true
             authme.admin.purge: true
    authme.register:
        description: Register an account
        default: true
    authme.login:
        description: Login into a account
        default: true
    authme.changepassword:
        description: Change password of a account
        default: true
    authme.logout:
        description: Logout
        default: true
    authme.passpartu:
        description: passpartu
        default: true        
    authme.allow2accounts:
        description: allow more accounts for same ip
        default: false
    authme.unregister:
        description: unregister your account
        default: true
    authme.admin.reload:
        description: AuthMe reload commands
        default: op
    authme.admin.register:
        description: AuthMe register command
        default: op
    authme.admin.changepassword:
        description: AuthMe changepassword command
        default: op
    authme.admin.unregister:
        description: AuthMe unregister command
        default: op
    authme.admin.purge:
        description: AuthMe unregister command
        default: op
    authme.admin.convertflattosql:
        description: Convert File to Sql method
        default: op
    authme.admin.convertfromrakamak:
        description: Convert from Rakamak database to AuthMe
        default: op
    authme.admin.lastlogin:
        description: Get last login date about a player
        default: op